Repository BCDA-APS/apstools, pull requests merged in 2022-01, with the labels that each got.

#615 add slit support
  .coverage
  CHANGES.rst
  MANIFEST.in
  apstools/devices/__init__.py
  apstools/devices/tests/test_xia_slit.py
  apstools/devices/xia_slit.py
  apstools/synApps/__init__.py
  apstools/synApps/db_2slit.py
  apstools/synApps/tests/test_2slit.py
  apstools/utils/__init__.py
  apstools/utils/slit_core.py
  docs/source/api/_devices.rst
  docs/source/api/_utils.rst
  docs/source/api/synApps/_db_2slit.rst
  docs/source/index.rst
  setup.cfg
Labels: enhancement

#617 add luascript support
  .coverage
  apstools/synApps/__init__.py
  apstools/synApps/_common.py
  apstools/synApps/luascript.py
  apstools/synApps/tests/test_luascript.py
  docs/source/api/synApps/_luascript.rst
  docs/source/api/synApps/index.rst
Labels: enhancement

#620 unit tests for PVPositionerSoftDone, et al.
  .coverage
  .github/workflows/unit-tests-pytest.yml
  .gitignore
  CHANGES.rst
  apstools/__init__.py
  apstools/devices/positioner_soft_done.py
  apstools/devices/tests/test_positioner_soft_done.py
  apstools/synApps/tests/test_luascript.py
  conda/meta.yaml
  environment.yml
Labels: testing

#622 repair workflow
  apstools/devices/positioner_soft_done.py
  apstools/devices/tests/test_positioner_soft_done.py
Labels: bug

#623 re-arrange the synApps documentation
  apstools/devices/__init__.py
  apstools/synApps/__init__.py
  apstools/synApps/_common.py
  apstools/synApps/busy.py
  apstools/synApps/calcout.py
  apstools/synApps/db_2slit.py
  apstools/synApps/epid.py
  apstools/synApps/luascript.py
  apstools/synApps/save_data.py
  apstools/synApps/sscan.py
  apstools/synApps/sseq.py
  apstools/synApps/swait.py
  apstools/synApps/transform.py
  docs/source/api/synApps/__common.rst
  docs/source/api/synApps/_iocstats.rst
  docs/source/api/synApps/_save_data.rst
  docs/source/api/synApps/index.rst
Labels: enhancement, documentation

#625 Linkam T96: turn on heating when setpoint is changed
  apstools/devices/linkam_controllers.py
Labels: enhancement

#624 Remove auto_heater and tweaks to PVPositionerSoftDone
  apstools/devices/lakeshore_controllers.py
  apstools/devices/positioner_soft_done.py
  apstools/devices/tests/test_positioner_soft_done.py
Labels: enhancement

#626 support more synApps structures
  .github/workflows/unit-tests-pytest.yml
  CHANGES.rst
  apstools/devices/__init__.py
  apstools/devices/tests/test_eurotherm_2216e.py
  apstools/devices/tests/test_xia_slit.py
  apstools/plans/tests/test_issue606.py
  apstools/synApps/__init__.py
  apstools/synApps/scalcout.py
  apstools/synApps/sub.py
  apstools/synApps/tests/test_2slit.py
  apstools/synApps/tests/test_calcout.py
  apstools/synApps/tests/test_iocstats.py
  apstools/synApps/tests/test_luascript.py
  apstools/synApps/tests/test_scalcout.py
  apstools/synApps/tests/test_sseq.py
  apstools/synApps/tests/test_sub.py
  apstools/synApps/tests/test_swait.py
  apstools/tests/__init__.py
  docs/source/api/synApps/_scalcout.rst
  docs/source/api/synApps/_sub.rst
  docs/source/api/synApps/index.rst
Labels: enhancement

#630 update Jupyter notebooks in the repository
  apstools/__init__.py
  docs/source/api/_filewriters.rst
  docs/source/resources/demo_nscan.ipynb
  docs/source/resources/demo_nxapswriter.txt
  docs/source/resources/demo_nxwriter_baseline.txt
  docs/source/resources/demo_nxwriter_bluesky.txt
  docs/source/resources/demo_nxwriter_metadata.txt
  docs/source/resources/demo_nxwriter_stream_primary.txt
  docs/source/resources/demo_nxwriter_tree.txt
  docs/source/resources/demo_specdata.dat
  docs/source/resources/demo_specfile_example.ipynb
  docs/source/resources/demo_tuneaxis.ipynb
  docs/source/resources/excel_scan.ipynb
  docs/source/resources/lesson3.ipynb
  docs/source/resources/spec1.dat
  docs/source/resources/test_specdata.txt
  examples/axis_tuning.ipynb
  examples/excel_scan.ipynb
  examples/sample_example.xlsx
  examples/tomo_issue49.ipynb
Labels: documentation

#603 Support Lakeshore temperature controllers 336 & 340
  CHANGES.rst
  apstools/devices/__init__.py
  apstools/devices/lakeshore_controllers.py
  apstools/devices/positioner_soft_done.py
  apstools/devices/tests/test_lakeshores.py
  apstools/devices/tests/test_positioner_soft_done.py
  docs/source/api/_devices.rst
Labels: enhancement, maintenance

#633 Move `enable` Component out from synApps Record devices
  apstools/devices/__init__.py
  apstools/devices/positioner_soft_done.py
  apstools/devices/tests/test_positioner_soft_done.py
  apstools/synApps/__init__.py
  apstools/synApps/_common.py
  apstools/synApps/calcout.py
  apstools/synApps/luascript.py
  apstools/synApps/scalcout.py
  apstools/synApps/sseq.py
  apstools/synApps/sub.py
  apstools/synApps/swait.py
  apstools/synApps/tests/test_2slit.py
  apstools/synApps/tests/test_calcout.py
  apstools/synApps/tests/test_iocstats.py
  apstools/synApps/tests/test_luascript.py
  apstools/synApps/tests/test_scalcout.py
  apstools/synApps/tests/test_sseq.py
  apstools/synApps/tests/test_sub.py
  apstools/synApps/tests/test_swait.py
  apstools/synApps/transform.py
  apstools/tests/__init__.py
  apstools/utils/tests/test_listdevice.py
  docs/source/api/synApps/index.rst
  docs/source/resources/demo_nscan.ipynb
  docs/source/resources/demo_specfile_example.ipynb
Labels: bug

#634 renew the unit tests for PVPositionerSoftDoneWithStop
  apstools/devices/tests/test_positioner_soft_done.py
  apstools/synApps/tests/test_calcout.py
  apstools/synApps/tests/test_luascript.py
  apstools/synApps/tests/test_scalcout.py
  apstools/synApps/tests/test_sseq.py
Labels: bug
