Repository BCDA-APS/apstools, pull requests merged in 2023-05, with the labels that each got.

#854 Add dates for the APS-U dark year and first operating cycle after
  apstools/devices/aps_cycle_info.yml
  apstools/devices/tests/test_aps_cycle.py
Labels: bug

#848 add support for fb epid database in optics
  CHANGES.rst
  apstools/devices/positioner_soft_done.py
  apstools/synApps/__init__.py
  apstools/synApps/epid.py
  apstools/synApps/tests/test_2slit.py
  apstools/synApps/tests/test_epid.py
  docs/source/api/synApps/_epid.rst
Labels: enhancement

#856 repair failing unit test
  apstools/synApps/tests/test_epid.py
Labels: bug

#857 add shutter tests and make PSS shutter more flexible
  CHANGES.rst
  apstools/devices/shutters.py
  apstools/devices/tests/test_lakeshores.py
  apstools/devices/tests/test_shutters.py
Labels: enhancement, testing

#858 resolve AD ERROR reports "capture not supported in Single mode"
  CHANGES.rst
  apstools/devices/area_detector_support.py
  apstools/devices/tests/conftest.py
  apstools/devices/tests/test_adsingle.py
  apstools/devices/tests/test_area_detector_support.py
  apstools/devices/tests/test_kohzu_monochromator.py
  apstools/plans/tests/test_plans.py
  apstools/tests/__init__.py
  apstools/utils/tests/test_listdevice.py
Labels: bug

#861 add 'ensure_AD_plugin_primed()' function
  CHANGES.rst
  apstools/callbacks/tests/test_nxwriter.py
  apstools/devices/__init__.py
  apstools/devices/area_detector_support.py
  apstools/devices/tests/conftest.py
  apstools/devices/tests/test_SingleTrigger_V34.py
  apstools/devices/tests/test_issue651.py
  docs/source/api/_devices.rst
  docs/source/examples/de_0_adsim_hdf5_basic.ipynb
  docs/source/examples/de_1_adsim_hdf5_custom_names.ipynb
  docs/source/examples/de_2_adsim_hdf5_single_mode.ipynb
Labels: enhancement

#862 define common IOC prefixes in one place
  apstools/callbacks/tests/test_i806_nxwriter.py
  apstools/callbacks/tests/test_nxwriter.py
  apstools/devices/tests/test_SingleTrigger_V34.py
  apstools/devices/tests/test_dict_device.py
  apstools/devices/tests/test_epics_scan_id_signal.py
  apstools/devices/tests/test_eurotherm_2216e.py
  apstools/devices/tests/test_flyer_motor_scaler.py
  apstools/devices/tests/test_issue651.py
  apstools/devices/tests/test_kohzu_monochromator.py
  apstools/devices/tests/test_lakeshores.py
  apstools/devices/tests/test_positioner_soft_done.py
  apstools/devices/tests/test_shutters.py
  apstools/devices/tests/test_xia_slit.py
  apstools/plans/tests/test_alignment.py
  apstools/plans/tests/test_labels_to_streams.py
  apstools/plans/tests/test_nscan.py
  apstools/plans/tests/test_run_blocking_function_plan.py
  apstools/plans/tests/test_sscan_support.py
  apstools/synApps/tests/test_2slit.py
  apstools/synApps/tests/test_calcout.py
  apstools/synApps/tests/test_epid.py
  apstools/synApps/tests/test_iocstats.py
  apstools/synApps/tests/test_luascript.py
  apstools/synApps/tests/test_scalcout.py
  apstools/synApps/tests/test_sseq.py
  apstools/synApps/tests/test_sub.py
  apstools/synApps/tests/test_swait.py
  apstools/tests/__init__.py
  apstools/utils/tests/test_connect_pvlist.py
  apstools/utils/tests/test_findpv.py
  apstools/utils/tests/test_listdevice.py
  apstools/utils/tests/test_listruns_i776.py
  docs/source/examples/pl_lineup.ipynb
Labels: maintenance, testing

#846 Added try...except for unconnected components when using apstools.uti…
  apstools/utils/device_info.py
Labels: enhancement

#864 add unit tests for new code in ``listdevice()``
  CHANGES.rst
  apstools/tests/__init__.py
  apstools/utils/device_info.py
  apstools/utils/tests/test_listdevice.py
Labels: testing
