Repository BCDA-APS/apstools, pull requests merged in 2024-07, with the labels that each got.

#988 Wrote new support for the planar undulator.
  apstools/devices/__init__.py
  apstools/devices/aps_undulator.py
  apstools/devices/tests/test_aps_undulator.py
Labels: hoist

#993 various fixes
  .github/workflows/code.yml
  CHANGES.rst
  apstools/devices/aps_undulator.py
  environment.yml
Labels: bug, testing

#995 add RevolverInsertionDevice
  apstools/devices/aps_undulator.py
Labels: maintenance

#996 add STI_Undulator class
  CHANGES.rst
  apstools/devices/aps_undulator.py
Labels: enhancement

#998 resume use of davidslusser/actions_python_ruff workflow action
  .github/workflows/code.yml
Labels: maintenance

#999 adjust the docstring to import write_stream
  apstools/plans/doc_run.py
Labels: documentation

#1000 remove (unused) root-level requirements* files.
  requirements-dev.txt
  requirements.txt
Labels: task

#1001 Suggest .component_names as another way to learn more
  docs/source/examples/ho_list_control_objects.ipynb
Labels: documentation

#1002 2M & 4M undulators
  apstools/devices/__init__.py
  apstools/devices/aps_undulator.py
  apstools/devices/tests/test_aps_undulator.py
  apstools/tests/__init__.py
  docs/source/api/_devices.rst
Labels: task

#1004 Fix typo in PV name for synApps SaveData() class
  apstools/synApps/save_data.py
Labels: bug
