Repository BCDA-APS/apstools, pull requests merged in 2024-01, with the labels that each got.

#901 BUG: Sphinx failed to import labjack
  apstools/devices/labjack.py
Labels: bug

#902 add acalcout record and userArrayCalcs
  CHANGES.rst
  apstools/synApps/__init__.py
  apstools/synApps/acalcout.py
  apstools/synApps/tests/test_acalcout.py
  docs/source/api/synApps/_acalcout.rst
Labels: enhancement

#903 Resolve ValueError from devices.area_detector_support
  CHANGES.rst
  apstools/devices/area_detector_support.py
  apstools/utils/__init__.py
  apstools/utils/misc.py
  apstools/utils/tests/test_utils.py
Labels: bug

#904 Hoist simulated controllers from bluesky_training
  apstools/devices/simulated_controllers.py
  apstools/devices/tests/test_simulated_controllers.py
Labels: enhancement

#907 listdevice(show_pv=True) alternate defaults
  CHANGES.rst
  apstools/utils/__init__.py
  apstools/utils/device_info.py
  apstools/utils/misc.py
  apstools/utils/tests/test_listdevice.py
  apstools/utils/tests/test_utils.py
  docs/source/api/_utils.rst
Labels: enhancement

#908 NXWriter should link title from metadata, if available
  .github/workflows/unit_tests.yml
  apstools/callbacks/nexus_writer.py
Labels: task

#913 rename the workflow files: simple, generic names
  .github/workflows/code.yml
  .github/workflows/docs.yml
  .github/workflows/pypi.yml
Labels: task

#910 Settling times for the SR-570 Preamplifier
  apstools/devices/srs570_preamplifier.py
  apstools/devices/tests/test_srs570_preamplifier.py
Labels: maintenance
