Repository BCDA-APS/apstools, pull requests merged in 2024-02, with the labels that each got.

#918 DOC: minor edits to documentation about exception handling
  docs/source/examples/ho_contingency.ipynb
Labels: documentation

#920 lineup2() should work with low intensity peaks
  CHANGES.rst
  apstools/callbacks/scan_signal_statistics.py
  apstools/plans/alignment.py
  apstools/plans/tests/test_alignment.py
Labels: bug

#929 add pipefail to CI workflows
  .github/dependabot.yml
  .github/disabled/codeql.yml
  .github/disabled/linter.yml
  .github/publish_anaconda.yml
  .github/workflows/code.yml
  .github/workflows/docs.yml
  .github/workflows/pypi.yml
  CHANGES.rst
  apstools/callbacks/scan_signal_statistics.py
  apstools/devices/srs570_preamplifier.py
Labels: bug

#928 remove problematic nested formatting in notebooks
  docs/source/examples/de_0_adsim_hdf5_basic.ipynb
  docs/source/examples/de_scaler_motor_flyer.ipynb_i763
  docs/source/examples/fw_specfile_example.ipynb
  docs/source/examples/ho_contingency.ipynb
  docs/source/examples/ho_list_control_objects.ipynb
  docs/source/examples/pl_excel_scan.ipynb
Labels: bug

#934 HHL Slits Added to APS Tools
  CHANGES.rst
  apstools/devices/__init__.py
  apstools/devices/hhl_slits.py
  docs/source/api/_devices.rst
Labels: enhancement

#930 Switch linting to use ruff
  .github/workflows/code.yml
  .ruff.toml
  CHANGES.rst
  apstools/devices/tests/test_SingleTrigger_V34.py
  apstools/devices/tests/test_aps_data_management.py
  apstools/devices/tests/test_mc_tc32.py
  apstools/plans/tests/test_issue606.py
  apstools/plans/tests/test_run_blocking_function_plan.py
  apstools/plans/tests/test_sscan_support.py
  apstools/utils/apsu_controls_subnet.py
  apstools/utils/tests/test_listdevice.py
  apstools/utils/tests/test_listplans.py
Labels: task
