Repository BCDA-APS/apstools, pull requests merged in 2024-04, with the labels that each got.

#942 example scans with sscan record
  docs/source/examples/de_sscan.ipynb
  docs/source/examples/scaler16.png
  docs/source/examples/sscan-scaler-v-motor.png
Labels: documentation

#917 SR-570 race condition
  apstools/devices/srs570_preamplifier.py
  apstools/devices/tests/test_srs570_preamplifier.py
Labels: bug

#956 Make the home page friendlier
  .github/workflows/docs.yml
  CHANGES.rst
  docs/requirements.txt
  docs/source/api/_callbacks.rst
  docs/source/api/_devices.rst
  docs/source/api/_filewriters.rst
  docs/source/api/_plans.rst
  docs/source/api/_utils.rst
  docs/source/api/index.rst
  docs/source/api/synApps/index.rst
  docs/source/changes.rst
  docs/source/conf.py
  docs/source/examples/device_examples.rst
  docs/source/examples/download_examples.rst
  docs/source/examples/filewriter_examples.rst
  docs/source/examples/howto_examples.rst
  docs/source/examples/index.rst
  docs/source/examples/pl_run_command_list.rst
  docs/source/examples/plan_examples.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/overview.rst
Labels: documentation

#958 mesh_grid feature for 8-ID
  CHANGES.rst
  apstools/plans/__init__.py
  apstools/plans/xpcs_mesh.py
  docs/source/api/_plans.rst
  environment.yml
  pyproject.toml
Labels: enhancement

#943 Edge align Function created
  .ruff.toml
  CHANGES.rst
  apstools/plans/__init__.py
  apstools/plans/alignment.py
  docs/source/api/_plans.rst
  docs/source/conf.py
  environment.yml
  pyproject.toml
  requirements.txt
Labels: enhancement
